;; Raymarcher! -currently broken-

(in-package :cepl)
(defparameter *gpu-array* nil)
(defparameter *vertex-stream* nil)
(defparameter *loop* 0.0)

(defsfun sphere ((p :vec3) (r :float)) 
  (return (- (length p) r)))

(defsfun box ((p :vec3) (b :vec3)) 
  (let ((d (- (abs p) b)))
    (return (+ (min (max (x d) (max (y d) (z d))) 0.0)
               (length (max d 0.0))))))

(defsfun thing2 ((p :vec3) (r :float) (l :float)) 
  (return (+ (* 0.2 (+ (y p)
                       (sin (+ (* (+ (cos l) 8.0) 
                                  (* 2 (x p))) l))))
             (- (length p) r))))

(deffshader frag ((posxy :vec2) &uniform (loop :float) (eye-pos :vec3))
  (let* ((eye-pos (v! 0.0 0.0 -5.0))
         (eye-dir (normalize (v! (x posxy) (y posxy) 1.0)))
         (e eye-pos)
         (output (v! 0.0 0.0 0.0)))
    (for (i 0) (< i 20) (++ i)
         (let ((d (thing2 e 1.4 loop)))
           (if (<= d 0.0)
               (let ((norm (density-normal (thing2 e 1.4 loop) 0)))
                 (setf output (v! (+ 0.3 (* 0.5 (y norm)))
                                  0.0
                                  (+ 0.5 (* 0.2 (mix (y norm) (x norm)
                                                     (sin (* 1.0 loop))))) ))
                 (break)))
           (setf d (max d 0.01))
           (setf e (+ e (* eye-dir d)))))
    (out output-color (v! output 1.0))))

(defpipeline prog-1 ((position :vec4) &uniform (loop :float) (eye-pos :vec3))
  (:vertex (setf gl-position position) (out posxy (swizzle position :xy)))
  frag)

(let ((running nil))
  (defun run-demo ()
    (cgl:clear-color 0.0 0.0 0.0 0.0)
    (setf *gpu-array* (make-gpu-array (list (v! -1.0  -1.0  0.0  1.0)
                                            (v!  1.0  -1.0  0.0  1.0)
                                            (v!  1.0   1.0  0.0  1.0)
                                            (v!  1.0   1.0  0.0  1.0)
                                            (v! -1.0   1.0  0.0  1.0)
                                            (v! -1.0  -1.0  0.0  1.0))
                                      :element-type :vec4
                                      :dimensions 6))
    (setf *vertex-stream* (make-vertex-stream *gpu-array*))
    (setf running t)
    (loop :while running :do
       (case-events (event) (:quit () (setf running nil)))
       (update-swank)
       (continuable (draw *vertex-stream*))))
  (defun stop-demo () (setf running nil)))

(defun draw (gstream)
  (setf *loop* (+ 0.01 *loop*))
  (gl:clear :color-buffer-bit)
  (gmap #'prog-1 gstream :loop *loop* :eye-pos (v! 0 0 -5))
  (gl:flush)
  (cgl:update-display))


(defsmacro density-normal (object-call position-arg-num)
  (when (not (listp object-call)) (error "object-call form must a list"))
  (let ((p (1+ position-arg-num))
        (oc object-call))
    `(normalize 
      (v! (- ,(utils:replace-nth oc p `(+ ,(nth p oc) (v! 0.01  0.0  0.0)))
             ,(utils:replace-nth oc p `(- ,(nth p oc) (v! 0.01  0.0  0.0))))
          (- ,(utils:replace-nth oc p `(+ ,(nth p oc) (v!  0.0 0.01  0.0)))
             ,(utils:replace-nth oc p `(- ,(nth p oc) (v!  0.0 0.01  0.0))))
          (- ,(utils:replace-nth oc p `(+ ,(nth p oc) (v!  0.0  0.0 0.01)))
             ,(utils:replace-nth oc p `(- ,(nth p oc) (v!  0.0  0.0 0.01))))))))
